import type { Metadata } from "next";
import "./globals.css";
import NavigationBar from "./components/NavigationBar";
import LinkContainer from "./components/LinkContainer";
import Footer from "./components/shared/Footer";

export const metadata: Metadata = {
  title: "Bella & Pepper e-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="nord">
      <body>
        <NavigationBar/>
        <LinkContainer/>
        {children}
        <Footer/>
        <link href="https://cdn.jsdelivr.net/npm/daisyui@4.12.13/dist/full.min.css" rel="stylesheet" type="text/css" />
      </body>
    </html>
  );
}
